### ISSUE TITLE
Unnecessary DESCRIPTION file

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet-gallery#14]
I believe [this file](https://github.com/UptakeOpenSource/pkgnet-gallery/blob/master/DESCRIPTION) was copied over from `pkgnet` inadvertently. I think that is should be removed from this repository, and that `LICENSE` should be updated to the complete text of the BSD 3-clause license (example: https://github.com/UptakeOpenSource/airflow-api/blob/master/LICENSE), with Copyright year 2018-2019.

**Comment by jayqi** [comment]
@jameslamb I don't think so, given that you can see from its commit history that @bburns632 is deliberately updating it. I think it's there for pkgdown metadata.

**Comment by jameslamb** [comment]
Could you point me to a point in this repo's code where it is getting using? I probably just don't understand how `pkgdown` works

**Comment by bburns632** [comment]
[pkgnet::build_articles()](https://pkgdown.r-lib.org/reference/build_articles.html) needs a description file within the package root directory.  I copied the `pkgnet` one over here for that purpose.  I am updating it to align with `pkgnet` as @jayqi noticed.  

We need it for now until a better solution exists.

**Comment by bburns632** [comment]
Also, here is where this repo utilizes that function. 

https://github.com/UptakeOpenSource/pkgnet-gallery/blob/master/pkgnet_build_gallery.R#L12
