### ISSUE TITLE
Unnecessary license text

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/pkgnet-gallery#16]
@bburns632 I believe this header legal text is unnecessary: https://github.com/UptakeOpenSource/pkgnet-gallery/blob/master/create_exhibit.R#L2

All code in this repo is covered by the file `LICENSE` plus the use of a `DESCRIPTION` file that references combining that file with the standard BSD 3-Clause license

**Comment by bburns632** [comment]
@jameslamb I see the `DESCRIPTION` file eventually going away with a better, future solution (it is not for this repo).  As with most things legal, it may redundant, but I'd rather keep it for now.
